version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
init:
- ps: git config --global core.autocrlf true
before_build:
- ps: nuget restore RichTextControls\RichTextControls.sln
build:
  verbosity: minimal
